version: "2"
services:
  retropie:
    volumes:
    build: .
    volumes:
      - /dev/snd:/dev/snd
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - $HOME/RetroPie/.emulstation:/home/pi/.emulstations
      - $HOME/RetroPie:/home/pi/RetroPie
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISPLAY=unix
    privileged: true
    command: emulationstation
